### ISSUE TITLE
Profile last updated date field is not returning data in Contacts

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#46]
In `Contacts` object, the `Profile last updated` date field is not returning any data.

**Comment by miasmos** [comment]
Fixed `Profile last updated` date field is not returning any data.

**Comment by asirota** [comment]
@stephenpoole - are you seeing any data return in this field? After testing on the sandbox I still don't see any data being returned? I see null on all the rows in the sandbox.

Testing on my record with `https://api.wildapricot.org/v2.1/accounts/221748/contacts/37415038` I see


` {
      "FieldName": "Profile last updated",
      "Value": "2019-12-11T15:49:51.553-05:00",
      "SystemCode": "LastUpdated"
    },`

**Comment by miasmos** [comment]
@asirota I am indeed, I'm looking at `HEAD` after pasting the latest v2.0 and seeing `Profile last updated` being populated for that user. Were you testing on what I had deployed to uat? That only included the changes for `feature/6`.
![Untitled-1](https://user-images.githubusercontent.com/3344159/76482104-9b2a6c80-63e9-11ea-989b-cd1e0fac35f8.jpg)

**Comment by asirota** [comment]
this is working now with 1.96 deployed
